### ISSUE TITLE
genepop_treemix

### ISSUE THREAD

**Issue by adriancasanovachiclana** [rystanley/genepopedit#10]
Hi,
First of all thanks a lot for this package.

I run this command (Rstudio with R version 3.5.1; Ubuntu 16.04LTS) but there were problems:

genepop_treemix("input_genepopedit_4360.txt",where.plink = "/plink2_path/", where.pgdspider = "/PGDSpider_2.1.1.5/" ,keep_inter = TRUE,allocate.pgd.ram = 1, path = paste0(output_dir,"treemix_input_genepopedit_4360.txt"))

**SCREEN INFO**

Converting GENEPOP to PED format for PLINK. Note that this step will format data needed to execute the Phyton conversions. Refer to TREEMIX documentation for Phython conversion workflow and scripting

             
Warning messages are expected as part of conversion process using PGDspider. Note this process can be inhibited by inadequate system resources.

             
INFO  13:02:38 - load PGDSpider configuration from: /home/adrian/Descargas/PGDSpider_2.1.1.5/spider.conf.xml
**Warning: Could not get charToByteConverterClass!**
initialize convert process...
read input file...
read input file done.
write output file...
WARN  13:02:39 - The name of a population was missing (no name attribute). It is now recoded as "pop_1"
WARN  13:02:40 - The name of a population was missing (no name attribute). It is now recoded as "pop_2"
WARN  13:02:40 - The name of a population was missing (no name attribute). It is now recoded as "pop_3"
WARN  13:02:40 - The name of a population was missing (no name attribute). It is now recoded as "pop_4"
WARN  13:02:40 - The name of a population was missing (no name attribute). It is now recoded as "pop_5"
WARN  13:02:40 - The name of a population was missing (no name attribute). It is now recoded as "pop_6"
write output file done.

             
PLINK v2.00a2 SSE4.2 (2 Oct 2018)              www.cog-genomics.org/plink/2.0/
(C) 2005-2018 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to BinaryPED.log.
Options in effect:
  --file PGDtest
  --make-bed
  --noweb
  --out BinaryPED

Start time: Wed Oct 17 13:02:40 2018
**Error: Unrecognized flag ('--file').**
For more info, try 'plink2 --help [flag name]' or 'plink2 --help | more'.

Converted ped file to binary ped.

            
**Error in file(file, "rt") : cannot open the connection
 Warning message:
In file(file, "rt") :
  impossible open file '/home/adrian/Descargas/plink2/BinaryPED.fam': Do not exist the file or directory**

**Comment by rystanley** [comment]
Adrian,

Thanks for pointing out this issue. It appears you are using the new version of Plink (2.0) which was that was recently released. Unfortunately this update has not yet incorporated the use of the **--file** command which  **genepop_treemix** and other genepopedit-plink related functions use. For now, the best bet would be for you to install **Plink 1.9** for this conversion process and update the where.plink variable to Plink 1.9 executable. 

We will update **genepop_treemix**, **genepop_colony**, **genepop_toploci** and **genepop_filter_maf** to work with Plink 2.0 hopefully in the near future. For the time being, I have updated the README to reflect the incompatibility and have added warnings to each function. 

Glad you are finding genepopedit useful. Thanks again for bringing this issue to our attention.
Cheers,

Ryan
