### ISSUE TITLE
Github actions and R-CMD-checks

### ISSUE THREAD

**Issue by thierrygosselin** [rystanley/genepopedit#14]
Hey Ryan,
Hope you're doing well.
Try the _new_ Github actions to make the testing... It's easier than Travis CI and AppVeyor and tests for all 3 OS...

`??usethis::use_github_actions`

Cheers
Thierry

**Comment by rystanley** [comment]
Thanks Thierry! I need to do a bit of an overhaul on genepopedit soon. I will incorporate those changes. 

Hope all is well with you. We should catch up sometime soon. 

Ryan
